#
# Configuración de Base de datos
#

### Desarrollo ###
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: arquitectura_development
  pool: 25
  username: admin
  password:
  host: 127.0.0.1
  wait_timeout: 300

### Pruebas ###
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: arquitectura_test
  pool: 50
  username: admin
  password:
  host: 127.0.0.1
  socket: /tmp/mysql.sock

### Production ###
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: arquitectura_production
  pool: 80
  username: admin
  password:
  host: 127.0.0.1