#
# Configuración de Base de datos
#

### Desarrollo ###
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DBDATABASE'] %>
  pool: 25
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>
  wait_timeout: 300

### Pruebas ###
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DBDATABASE'] %>
  pool: 50
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>
  socket: /tmp/mysql.sock

### Production ###
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DBDATABASE'] %>
  pool: 80
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>