---
:verbose: false
:concurrency: 25
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
staging:
  :concurrency: 50
production:
  :concurrency: 80
:queues:
  - 'default'
  - ['journaler',5]
  - ['businesslogic',4]
  - ['notifiers',3]